### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by dmi7ry** [kiith-sa/dmarkdown#5]
Can't build any project after added `"dmarkdown": { "version" : "~>0.1.0" }` to the dependencies.

dmd 2.067
> ..d-idioms> dub
Building dmarkdown 0.2.0 configuration "library", build type debug.
Running dmd...
C:\Users\Dmitry\AppData\Roaming\dub\packages\dmarkdown-.2.0\source\dmarkdown\markdown.d(275): Error: no property 'joiner' for type 'Take!(Repeat!string)'
C:\Users\Dmitry\AppData\Roaming\dub\packages\dmarkdown-.2.0\source\dmarkdown\markdown.d(278): Error: no property 'map' for type 'Block[]'
FAIL C:\Users\Dmitry\AppData\Roaming\dub\packages\dmarkdown-0.2.0\.dub\build\library-debug-windows-x86-dmd_2067-1564E97DABD8A03ACA3F1B08A8738B6E\ dmarkdown staticLibrary
Error executing command run: dmd failed with exit code 1.

**Comment by kiith-sa** [comment]
Should be fixed by https://github.com/kiith-sa/dmarkdown/commit/4a2af6b0caf314d94f282d8c8c5de.
