### ISSUE TITLE
Build hmod error 'no property'

### ISSUE THREAD

**Issue by deviator** [kiith-sa/dmarkdown#7]
In file `source/dmarkdown/markdown.d` at line where import `std.algorithm` need add `map` and `joiner`
like this
`import std.algorithm : joiner, map, canFind, countUntil, min;`

**Comment by kiith-sa** [comment]
Thanks.

Fixed as of https://github.com/kiith-sa/dmarkdown/commit/4a2af6b0caf314d94f282d8c8c5de
